name: blokdijk
favicon: null
layout_spectrum: 0.7720317910425365
typography_spectrum: 0.6954532728996128
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1728077558800578
  lightness: 0.8796605179086328
  saturation: 0.20791094191372395
  rhythmicContrast: 0.6970542890485376
purpose: []
